# Generated by Django 3.0.8 on 2020-09-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='know',
            field=models.TextField(blank=True, null=True),
        ),
    ]
