# Generated by Django 3.0.8 on 2020-08-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create'], 'verbose_name': '博文管理', 'verbose_name_plural': '博文管理'},
        ),
    ]
