# Generated by Django 3.0.8 on 2020-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200826_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.CharField(choices=[('个人日记', '个人日记'), ('python', 'python'), ('django', 'django')], default='python', max_length=32),
        ),
    ]
