# Generated by Django 3.0.8 on 2020-08-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_article_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('转载', '转载'), ('原创', '原创')], default='原创', max_length=32),
        ),
    ]
