# Generated by Django 3.0.8 on 2020-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_article_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
