# Generated by Django 3.0.8 on 2020-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='img',
            field=models.URLField(default='https://www.yanshisan.cn/logo.png'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(),
        ),
    ]
