# Generated by Django 3.0.8 on 2020-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='article_img'),
        ),
    ]
