# Generated by Django 3.0.8 on 2020-09-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_article_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='picture',
            new_name='picture_url',
        ),
    ]
